### ISSUE TITLE
New App Unsupported but Can Access Device Model and Battery Level

### ISSUE THREAD

**Issue by zibo-chen** [SeanPesce/Suear-Web-Viewer#4]
Hello,

I've encountered an issue with a new app that is currently not supported. However, the app is capable of obtaining the device model and the battery level. For reference and further investigation, here is the link to the app on the Google Play Store: [https://play.google.com/store/apps/details?id=com.i4season.bkCamera_soulear&hl=en_US](https://play.google.com/store/apps/details?id=com.i4season.bkCamera_soulear&hl=en_US).

Could you please look into this matter?

Thank you for your assistance.

**Comment by SeanPesce** [comment]
Hi @zibo-chen, unfortunately it would be more effort than I'm willing to expend to statically reverse engineer the protocol purely from the APK code (at least in the near future). However, if you can get a packet capture of the traffic I might be able to work with that.

If fetching device information works, it could be something as simple as changing the port(s) the device uses for streaming ([see here](https://github.com/SeanPesce/Suear-Web-Viewer/blob/main/suear_mirror.py#L293)). Unfortunately I won't have time to look anytime soon, as the holidays are coming up *and* I'm currently in the process of moving across the country.

**Comment by zhisenyang** [comment]
@zibo-chen 
I also met the same problem.How did you deal with it?

**Comment by zibo-chen** [comment]
@zhisenyang I have not continued to attempt resolving the issue myself, but I have analyzed the code of two similar apps and suspect that this app might simply be using a new port. I would recommend capturing the network traffic to verify this hypothesis.

**Comment by zhisenyang** [comment]
@zibo-chen 
I decompiled apk,I found a new port and it appears.
```
public int nitwifistart(Context context, String str, int i) {
    return wifistart(context, "192.168.1.1", "192.168.1.1", "10004", i);
}
```

**Comment by zibo-chen** [comment]
@zhisenyang Thank you for sharing your findings. It seems like the new port "10004" could be the key to the issue. If that's the case and it resolves the problem, I think that we can close this issue.

**Comment by zhisenyang** [comment]
@zibo-chen Can you share any new progress in a timely manner? Thank you.

**Comment by zibo-chen** [comment]
@zhisenyang Apologies for any confusion. I haven't had the time to test further. I mistakenly thought changing the port might resolve the issue based on your findings. You might want to try updating the port in the code at https://github.com/SeanPesce/Suear-Web-Viewer/blob/main/suear_mirror.py#L293 to see if it works. Good luck!

**Comment by zhisenyang** [comment]
> @zhisenyang Apologies for any confusion. I haven't had the time to test further. I mistakenly thought changing the port might resolve the issue based on your findings. You might want to try updating the port in the code at https://github.com/SeanPesce/Suear-Web-Viewer/blob/main/suear_mirror.py#L293 to see if it works. Good luck!

I tried it, but it didn't work.╮(╯▽╰)╭
